### ISSUE TITLE
you can use to multi-line strings

### ISSUE THREAD

**Issue by bjrambo** [xlanor/SIM-UoW-Timetable-bot-LEGACY-#8]
https://github.com/xlanor/SIM-UoW-Timetable-bot/blob/81aee370656f8c12c1dcb141917bb1d3588462a9/commands.py#L49

```python
message = """ this is use to multi-lines..
so i can use to multi-lines... """.replace('\n', ' ')
```
use triple quotes to start and end them. You can change Enter to Space. `.replace`
also change Spance to Enter. 
`.replace('          ', '\n')` You can change it to enter according to the number of spaces.

from : https://stackoverflow.com/questions/10660435/pythonic-way-to-create-a-long-multi-line-string

**Comment by xlanor** [comment]
spliting """ """ will result in formatting issues with telegram, since the space when entering a new sentence is registered by telegram.
